name: Deploy to github pages
on:
  push:
    branches: [main]

jobs:
  build-and-deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          submodules: "recursive"
          lfs: true

      - name: Install and Build
        run: |
          cd app_web
          npm install
          npm run build

      - name: Check build size
        # 1GB = 1073741824 bytes
        run: |
          SIZE=$(du -s -B 1 app_web/dist/ | cut -f 1)
          echo $SIZE
          if [[ $SIZE -gt 1573741824 ]]; then echo 'dist folder exceeds limit of 1.5GB! Aborting'; exit 1; fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Build output to publish to the `gh-pages` branch:
          publish_dir: ./app_web/dist
          # The following lines assign commit authorship to the official
          # GH-Actions bot for deploys to `gh-pages` branch:
          # https://github.com/actions/checkout/issues/13#issuecomment-724415212
          # The GH actions bot is used by default if you didn't specify the two fields.
          # You can swap them out with your own user credentials.
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
